version: "2"

run:
  go: "1.24"
  modules-download-mode: vendor

linters:
  default: all
  disable:
    - cyclop
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - godox
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    errcheck:
      exclude-functions:
        - fmt:.*
    depguard:
      rules:
        debug_tools:
          deny:
            - pkg: "github.com/davecgh/go-spew"
              desc: debug statements should be removed

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
