linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - godox
    - gofumpt
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*

run:
  modules-download-mode: vendor
  timeout: 3m
  go: "1.24"
