name: 🐛 Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["type/bug", "action/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! The more detail you provide, the faster we can help.

        ## Tips for Reporting CLI Issues

        - Run your command with `-v`, `-vv`, or `-vvv` flags to get detailed output (more v's = more verbose)
        - Include the full command you ran, with all flags
        - Check your configuration: `grafanactl config view`
        - Try the command with `--dry-run` if applicable
        - Look for similar issues: [Search existing issues](https://github.com/grafana/grafanactl/issues)

  - type: input
    id: grafanactl_version
    attributes:
      label: grafanactl Version
      description: "Run `grafanactl version` to get this information"
      placeholder: "grafanactl version v0.1.0 (commit: abc123, built: 2025-01-15)"
    validations:
      required: true

  - type: dropdown
    id: affected_command
    attributes:
      label: Which command group is affected?
      options:
        - resources (get/list/push/pull/delete/edit/serve/validate)
        - config (set/unset/use-context/list-contexts/current-context/view/check)
        - General (installation, version, help)
        - Other
    validations:
      required: true

  - type: textarea
    id: command_executed
    attributes:
      label: Command Executed
      description: What command did you run? Include all flags and arguments
      placeholder: "grafanactl resources push --context=prod --dry-run ./dashboards/"
      render: shell
    validations:
      required: true

  - type: textarea
    id: command_output
    attributes:
      label: Command Output
      description: "Paste the full output. Run with -v, -vv, or -vvv for more details"
      placeholder: |
        Error: failed to push resource dashboard.v1alpha1.dashboard.grafana.app/my-dashboard
        Caused by: 403 Forbidden: insufficient permissions
      render: shell
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe what went wrong in your own words
      placeholder: |
        I was trying to push dashboards to production using grafanactl resources push,
        but the command failed with a permission error. I can push to staging fine
        using the same dashboards.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: What did you expect to happen?
      description: Help us understand the correct behavior
      placeholder: The dashboards should have been successfully pushed to the production Grafana instance
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: How can we reproduce this?
      description: Step-by-step instructions help us find the issue faster. Include commands exactly as you ran them.
      placeholder: |
        1. Set context: grafanactl config use-context prod
        2. Verify context: grafanactl config current-context
        3. Try to push: grafanactl resources push ./dashboards/
        4. Observe error: 403 Forbidden
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      description: This helps us understand the severity
      options:
        - Every time
        - Often (more than 50% of the time)
        - Sometimes (less than 50% of the time)
        - Only happened once or twice
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: "Operating system, shell, Grafana server version, Go version (if relevant)"
      placeholder: "macOS 14.1, zsh 5.9, Grafana Cloud (v12.0), Go 1.21"
    validations:
      required: true

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps Taken
      description: Have you tried these common debugging steps?
      options:
        - label: I ran the command with -v, -vv, or -vvv flag for verbose output
        - label: I checked my configuration with `grafanactl config view`
        - label: I verified I'm using the correct context with `config current-context`
        - label: I verified my authentication token/credentials are valid
        - label: I checked the documentation for this command

  - type: textarea
    id: context
    attributes:
      label: Anything else we should know?
      description: Additional context, workarounds you've found, when this started happening, relevant configuration details, etc.
      placeholder: |
        This started after upgrading to grafanactl v0.2.0.
        I found that using --max-concurrent=1 makes it work, but it's very slow.
        My config uses token authentication with a service account token...
