name: ⚙️ Configuration Issue
description: Problems with grafanactl configuration, contexts, or authentication
title: "[Config]: "
labels: ["type/configuration", "action/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Having trouble with configuration, contexts, or authentication? This template will help us assist you faster.

        ## Before You Submit

        - Make sure you're using Grafana 12 or above (grafanactl doesn't support older versions)
        - Check the [configuration documentation](https://grafana.github.io/grafanactl/)
        - Remove any tokens, passwords, or sensitive data before pasting configuration

  - type: input
    id: grafanactl_version
    attributes:
      label: grafanactl Version
      description: "Run `grafanactl version`"
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: dropdown
    id: config_issue_type
    attributes:
      label: What type of configuration issue is this?
      options:
        - Authentication/authorization (401, 403 errors)
        - Context management (switching contexts, current-context issues)
        - Server connection (can't reach Grafana server)
        - TLS/certificate issues
        - Namespace issues (org-id or stack-id problems)
        - Configuration file problems
        - Environment variable issues
        - Other
    validations:
      required: true

  - type: textarea
    id: config_view
    attributes:
      label: Current Configuration
      description: "Run `grafanactl config view` and paste the output. **IMPORTANT: Remove any tokens, passwords, or certificate data!**"
      placeholder: |
        contexts:
          - name: prod
            server: https://myorg.grafana.net
            namespace: stack-123
            auth-type: token
          - name: staging
            server: https://staging.example.com
            namespace: org-1
            auth-type: basic
        current-context: prod
      render: yaml
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: What's the problem?
      description: Describe the configuration issue you're experiencing
      placeholder: |
        I'm trying to connect to my Grafana Cloud instance, but authentication
        keeps failing with "401 Unauthorized" even though my token is valid.
        I can use the same token successfully in Postman...
    validations:
      required: true

  - type: textarea
    id: command_attempted
    attributes:
      label: Command That Failed
      description: What command did you try to run?
      placeholder: "grafanactl resources list dashboards --context=prod -vv"
      render: shell
    validations:
      required: true

  - type: textarea
    id: command_output
    attributes:
      label: Command Output
      description: "Paste the error message or output. Run with -v, -vv, or -vvv for more details."
      placeholder: |
        Error: failed to list resources
        Caused by: 401 Unauthorized: Invalid credentials
      render: shell
    validations:
      required: true

  - type: input
    id: grafana_version
    attributes:
      label: Grafana Server Version
      description: What version of Grafana are you connecting to?
      placeholder: "Grafana Cloud v12.0, or Grafana OSS v12.1"

  - type: checkboxes
    id: config_checks
    attributes:
      label: Configuration Checks
      description: Have you verified these common issues?
      options:
        - label: I verified my token/credentials are valid by testing in Grafana UI or with curl
        - label: I checked the server URL is correct and accessible (can reach it in a browser)
        - label: I confirmed I'm using Grafana 12 or above
        - label: I verified the namespace (org-id or stack-id) is correct
        - label: I checked `grafanactl config current-context` shows the expected context
        - label: I tried running the command with -v, -vv, or -vvv flag for verbose output

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Environment variables set, when this started happening, workarounds tried, etc.
      placeholder: |
        Environment variables I have set:
        - GRAFANA_TOKEN is set in my shell
        - GRAFANA_SERVER is not set

        This started happening after I rotated my service account token yesterday.
        The old token still works in Postman but not in grafanactl.
