name: CI
on:
  pull_request: ~
  push:
    branches: [main] # so that we build a Go cache that can be re-used in PRs

env:
  DEVBOX_VERSION: 0.14.0

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Restore go vendors
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf #v4.2.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-deps-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-deps-${{ runner.os }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 #v0.12.0
        with:
          enable-cache: 'true'
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Run golangci-lint
        run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Restore go vendors
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf #4.2.2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-deps-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-deps-${{ runner.os }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 #v0.12.0
        with:
          enable-cache: 'true'
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Tests
        run: make tests
