name: CI
on:
  pull_request: ~
  push:
    branches: [main] # so that we build a Go cache that can be re-used in PRs

env:
  DEVBOX_VERSION: 0.14.0

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Restore go vendors
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-deps-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-deps-${{ runner.os }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 #v0.12.0
        with:
          enable-cache: "true"
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Run golangci-lint
        run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Restore go vendors
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #4.2.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-deps-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-deps-${{ runner.os }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 #v0.12.0
        with:
          enable-cache: "true"
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Tests
        run: make tests

  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 #v0.12.0
        with:
          enable-cache: "true"
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Check for drift in the generated documentation references
        run: make cli-reference
        shell: bash

      - name: Build documentation
        run: make docs
